### ISSUE TITLE
IceRock KMM "Запуск проекта" #2 - замечания

### ISSUE THREAD

**Issue by ghost** [icerockdev/kmp-codelabs#19]
- [x] ["Сборка Android приложения"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#3) Не хватает объяснения как добавлять конфигурацию.
- [x] ["Сборка iOS приложения"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) В градле нет задачи syncMultiPlatformLibraryDebugFrameworkIosX64. 
- [x] статья ["Gradle для iOS разработчика"](https://kmm.icerock.dev/pages/4.1.1-kmm-ios-gradle/) на данный момент не доступна по этой ссылке
- [x] В статье ["Gradle для iOS разработчика"](https://kmm.icerock.dev/pages/4.1.1-kmm-ios-gradle/) ссылка на которую есть в шаге ["Сборка iOS"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4), написано, что задача добавляется плагином mobile-multiplatform. В лабе об этом плагине ничего не говорится. (говорится в [Запуск проекта](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#1) Настройка рабочего окружения)
- [x] Сделать сноску с пояснениями что Gradle Sync может пройти с ошибкой и тогда не будет конфигурации запуска андроида и задачи компиляции айоса + как с этим бороться
- [x]  поправить ссылки на теорию так, чтобы было понятно когда потребуется знания материала из них
- [x] Описать подробнее, что именно нужно редактировать в .zshenv  и как это можно делать: nano или любой другой редактор. Или в терминале ввести export JAVA_HOME=/Users/..... и аналогично для android sdk. Также показать пример контента этого файла. Указать команду, как проверить, что переменные окружения настроены правильно
- [x] В  разделе "Проверка наличия всех необходимых переменных окружения" пункта  ["Настройка рабочего окружения"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#1) добавить напоминалку "Открыть новую сессию терминала" т.к. в старой сессии новые переменные окружения отображаться не будут.
- [x] Описать как проверить какой JDK делает сборку Xcode
- [x] Пояснить, что делать с SigningConfig "release" is missing required property "storePassword".
- [x] В пунктах [4](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#3) или [5](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) надо показать на скриншоте где именно находится вкладка с задачами Gradle
- [x] ["Отладка Android"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#5) Указать, что для Android работа с дебаггером в общем коде ничем не отличается от привычного использования.
- [x] В некоторых местах надо указывать, что это актуально только для macOS (переменные окружения под windows указываются иначе)
- [x] [Настройка окружения](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#1) - CocoaPods по офф доке не удалось установить, воспользовался brew: {{brew cleanup -d -v }} brew install cocoapods (Добавить, что можно установить и таким образом)
- [x] Configure -> Default Project Structure - путь в переменной JAVA_HOME отличается от пути который выводится в терминале командой export после изменения ~/.zshenv. Проблему решил редактированием файла nano .bash_profile
- [x] Возможно имеет смысл поменять [5](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) и [6](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#5) пункты местами чтобы сначала собрать и отладить Android, а затем IOS
- [x] Добавить описание, как создавать симулятор
- [x] Было бы неплохо добавить сюда же конфигурацию воркеров и студии (?)
- [x] Добавить пояснение как проверить одинаковую ли JVM использует компилятор в  Android Studio и в Xcode (открыть Activity Monitor и посмотреть сколько там java процессов: если один то все гуд, если несколько - убить их и попробовать по новой скомпилить в xcode а потом в студии. Если опять станет 2 - значит разные. Тогда смотреть в export - там JAVA_HOME какой)
- [x] Если установлено несколько jdk, то Xcode будет запускать билд с рандомным. Поэтому важно оставить только jdk-11.
- [x] Ссылка с главной ведет просто на гитхаб компании, а надо наверное на этот репозиторий (DevTchernov) (?)
- [x] ./gradlew syncMultiPlatformLibraryDebugFrameworkIosArm64 команда для не работает из за настроек zsh , необходимо зайти в файл .zshenv открыть редактором и раскомментировать в самом начале
 If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH <- раскомментировать это. Повторяем  ./gradlew syncMultiPlatformLibraryDebugFrameworkIosX64 должно работать , если нет то менять настройки iTerm в разделе defaults
- [x] Если по какой-то причине поставилась не 11 jdk, а другая -  смотреть [сюда](https://java.tutorials24x7.com/blog/how-to-switch-java-version-on-mac)
- [x] Ошибка после pod install: error: Signing for "ios-app" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'ios-app' from project 'ios-app')
идем в настройки проекта -> TARGET -> ios-app -> BundleIdentifier и меняем org.example.app на другой Пример "org.example.app.my"
- [x] Исправить опечатки в тексте (В самом начале [4ого](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#3) пункта дублируется "достаточно")
- [x] На странице ["Cборка iOS"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) ссылка "Gradle для iOS разработчиков на kmm.icerock.dev" не открывается 
- [x] Сборка напрямую из Android Studio: отсутствуют следующие разделы Gradle - IOS Applecation (Решения не нашел, возможно не существенно)
- [x] При сборке приложения iOS нужно указать уникальный Bundle Identifier, при его смене файл GoogleService-Info-org.example.app.plist содержит уже невалидный бандл в названии и проект не собирается
- [x] добавить информацию про advanced debugging tips from Xcode like the `po println`

Не в рамках этой задачи: 
- Из-за того, что в разных EventListener в разных вью-моделях объявлена одинаковая функция, ios не собирается из-за redeclaration. Как это фиксить? [ошибка](https://gitlab.icerockdev.com/digital-insider/rosseti-mobile/-/jobs/116745#L5204) [обсуждение](https://icerockdev.slack.com/archives/C01GEHHMJL9/p1623400379030900) (Не уверен, что это сюда)
- Написать про это: (В rss-news интерфейс репозитория NewsListRepository лежит в mpp-lib:feature:news:list, а имплементация NewsListRepositoryImpl в mpp-lib:commonMain?) - да, интерфейс получения данных задает сама фича (чтобы уметь получать данные из вне). А реализация находится в mpp-library, в которой доступны классы всех фичей и происходит связывание всех компонентов воедино
- В пункте [5](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) в главе "Компиляция MultiPlatformLibrary.framework" можно немного пояснить что такое компиляция kotlin модуля. Мол, эта задача запускает компилятор Kotlin Native, который компилирует common и ios код в нативную статическую библиотеку, которая упаковывается в статический фреймворк вместе с ресурсами модуля, который и подключается к проекту xcode.
-  Добавить про то, что все мультиплатформенные библиотеки публикуются отдельными артефактами - common, android, iosx64, iosarm64 все это отдельные артефакты -  [тут](https://repo1.maven.org/maven2/dev/icerock/moko/) наглядно видно что каждая библиотека имеет пачку артефактов
- Описать, как "Gradle съел кастом GradlePlugin класс в plugins { plugin(Deps.Plugins.androidApplication) }" (GradlePlugin класс приходит из [mobile-multiplatform-plugin](https://github.com/icerockdev/mobile-multiplatform-gradle-plugin/blob/master/src/main/kotlin/GradlePlugin.kt) и в том же файле видно что для классов управления зависиомостями гредла добавлена функция plugin которая умеет принимать GradlePlugin)
- Добаивть про то, как работают commonMainImplementation() и androidMainImplementation() "работают как buildFlavors?" - commonMainImplementation и подобные работают не как buildFlavors, но похоже в чемто. buildFlavors'ов нет в Kotlin Multiplatform, это фича Android Gradle Plugin'а и все. А в KMM работает Kotlin Gradle Plugin, в котором есть поддержка Hierarhical Multiplatform с множеством source set'ов. и вот для каждого sourceset'а добавляются свои конфигурации для подключения зависимостей к конкретным сорссетам. Сами же сорссеты имеют иерархию, типа как у билдфлейворов. то есть androidMain видит все то что есть в commonMain. а iosArm64 видит все что в iosMain и все что в commonMain.  [Читать](https://kotlinlang.org/docs/mpp-dsl-reference.html#source-sets)

Исправлено: 
["Сборка iOS приложения"](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#4) Не получается выбрать схему. Error: Please specify Xcode project location in xcodeproj property of gradle.properties. Воможно из-за того, что с включенным Kmm плагигном не работает Gradle sync
Соответственно все, что связанно с запуском iOS из Android Studio не получилось сделать

**Comment by Alex009** [comment]
нужно:

- [x] сделать сноску с пояснениями что Gradle Sync может пройти с ошибкой и тогда не будет конфигурации запуска андроида и задачи компиляции айоса + как с этим бороться
- [x]  поправить ссылки на теорию так, чтобы было понятно когда потребуется знания материала из них
- [x] описать подробнее что нужно в `.zshenv` редактировать и как это можно делать (что не только nano можно использовать и пример контента в принципе показать) - "я обычно просто нахожу этот файл и открываю его через SublimeText и редактирую , тогда возник вопрос куда или где нужно вписать эту строку ?"
- [ ] указать команду для самопроверки правильности настройки переменных окружения там же, где настраиваем переменную окружения "а именно на вот этом этапе “На Welcome экране выбираем Configure -> Default Project Structure. И в появившемся экране выбираем JDK Location из JAVA_HOME:” у меня нет такого , предлагает следущий AndroidStudio.app -> Contents -> jre -> jdk -> Contents"
- [ ] описать как проверить какой JDK делает сборку Xcode

**Comment by FelixFalkovsky** [comment]
1. По окончанию этапа 3 дождаться сборки , появляется Алерт в просьбой обновить version 4.1.1 to version 4.2.0.  

2. Для места где  .zshenv могу выслать скриншот  как это сделано у меня . 

3. Сборка iOS 

  - pod install выдал ошибку   "далее действия делал в iTerm2 + zsh" 

 [!] CocoaPods could not find compatible versions for pod "FirebaseCrashlytics":
  In snapshot (Podfile.lock):
    FirebaseCrashlytics (= 7.10.0, ~> 7.3)

  In Podfile:
    MCRCStaticReporter (from `https://github.com/icerockdev/moko-crash-reporting.git`, tag `release/0.1.2`) was resolved to 0.1.0, which depends on
      FirebaseCrashlytics (~> 7.3)

None of your spec sources contain a spec satisfying the dependencies: `FirebaseCrashlytics (= 7.10.0, ~> 7.3), FirebaseCrashlytics (~> 7.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 
 - далее **pod update** не работает , удаляем Podfile.lock и запускаем снова pod install
 
 4. Компиляция MultiPlatformLibrary.framework (Kotlin модуль для iOS)
 
  ./gradlew syncMultiPlatformLibraryDebugFrameworkIosArm64 команда для не работает из за настроек zsh , необходимо зайти в файл .zshenv открыть редактором и раскомментировать в самом начале 
    # If you come from bash you might have to change your $PATH.
    export PATH=$HOME/bin:/usr/local/bin:$PATH            <- раскомментировать это .
    
    далее повторяем  ./gradlew syncMultiPlatformLibraryDebugFrameworkIosX64 должно работать , если нет то менять настройки iTerm в разделе defaults 
    
  5. Установка CocoaPods зависимостей вместе с MultiPlatformLibrary 
  
после pod install получил 

error: Signing for "ios-app" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'ios-app' from project 'ios-app')
"Есть скриншот если нужен вышлю"
идем в настройки проекта -> TARGET -> ios-app -> BundleIdentifier и меняем org.example.app на другой Пример "org.example.app.my"
    далее билдим проект command + B .

**Comment by FelixFalkovsky** [comment]
**Сборка напрямую из Android Studio** 
- отсутствуют следующие разделы Gradle
- IOS Applecation 
Решения не нашел , возможно не существенно.

**Comment by FelixFalkovsky** [comment]
**Построение навигации в iOS приложении**
Было бы не плохо добавить изображения как примеры. 

Создадим в ios-проекте папку src/Coordinators  исправить на src -> Common -> Coordinator  "и создавать нечего не нужно , ведь там уже описание есть"

Не хватает документирования методов и кода для лучшего восприятия //MARK: и ему подобные.

Отредактировать статью в местах где говориться что то сделать "Уже сделано!" либо удалить из проекта эти файлы.

Заменить часть скриншотов и лучше бы если бы они были полными а не кусками , восприятие другое.

**Comment by FelixFalkovsky** [comment]
**Пишем ViewModel**

Очень сложно сориентироваться за мыслью автора и того что происходит. Удобнее было бы разбить на этапы как это было сделано в разделе "Разворачивание проекта" . 
И хотелось бы прям с заведения папок для фичи , что бы построить цепочки логики действий на проекте. 

Так же полноценные скриншоты . 

Пишем логику для AuthViewModel 

- сначала добавляем Import 
- потом заводим переменные для полей и уж потом liveData 
- не показано где и как должен быть создан class Validation 

- далее после того как вынесли в отдельный класс Validation, в AuthViewModel добавляем 
import org.example.library.feature.auth.model.Validation 
и не делать их приватными 

- для следующего шага нам нужен эти импорты
import dev.icerock.moko.mvvm.livedata.all
import dev.icerock.moko.mvvm.livedata.*

- для следующего шага нужен 
import kotlinx.coroutines.launch

- не показано создание где и как создается AuthRepository!  P.S - видел AuthRepository в папках id и mode иl т.д что не есть хорошо. Далее после создания добавляем 
import org.example.library.feature.auth.model.AuthRepository
private val repository: AuthRepository 

- не мало важный момент разделять импорты 
import dev.icerock эти отдельно от этих  import org.example а не в куче .

**Comment by Alex009** [comment]
Ошибка 
```
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. 
For more information see https://docs.gradle.org/6.8.3/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
e: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel
```

причина
```
▶ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
▶ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home
```

вылечили
https://java.tutorials24x7.com/blog/how-to-switch-java-version-on-mac

а также:

> выводы. Почему-то ставится последняя jdk16. Я ставил 11. Возможно это из-за обновление astudio через jetb-toolbar. Еще android studio preview работает хорошо. Наверное буду её использовать. + очень продвинулся после отжатия экспериментальных чекбоксов в настройках (edited)

**Comment by Alex009** [comment]
также пояснить че делать с
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':android-app:packageDevRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storePassword".
```

**Comment by Alex009** [comment]
от @anton6tak

> В конце второго пункта, в "Проверка наличия всех необходимых переменных окружения" предлагаю добавить еще напоминалку "Открыть новую сессию терминала" т.к. в старой сессии новые переменные отображаться не будут.
> 
> Косметические изменения:
> 2 пункт) Доступен данный плагин только на macOS (так как запуск и отладка iOS приложения только на macOS возможна).
> -> Доступен данный плагин только на macOS (так как запуск и отладка iOS приложения возможна только на macOS).

**Comment by Alex009** [comment]
от @Tetraquark 

> - В пунктах 4 или 5 надо показать на скриншоте где именно находится вкладка с задачами Gradle
> - В пункте 5 в главе "Компиляция MultiPlatformLibrary.framework" можно немного пояснить что такое компиляция kotlin модуля. Мол, эта задача запускает компилятор Kotlin Native, который компилирует common и ios код в нативную статическую библиотеку, которая упаковывается в статический фреймворк вместе с ресурсами модуля, который и подключается к проекту xcode.
> - В пункте 6 про отладку на Android я бы первым абзацем просто написал, что для Android работа с дебаггером в общем коде ничем не отличается от привычного использования.

**Comment by Alex009** [comment]
от @RezMike

> в некоторых местах надо указывать, что это актуально только для macOS (переменные окружения под windows указываются иначе)

**Comment by Alex009** [comment]
от @FelixFalkovsky 

> основные проблемы были
> с zsh и import

**Comment by Alex009** [comment]
> - Настройка окружения - CocoaPods - по офф доке не удалось установить, воспользовался brew: 
> - {{brew cleanup -d -v }}
> - brew install cocoapods
> - Configure -> Default Project Structure - путь в переменной JAVA_HOME отличается от пути который выводится в терминале командой export после изменения ~/.zshenv. Проблему решил редактированием файла nano .bash_profile 
> - Больше всего времени ушло на настройку окружения ~1ч, но тут наверное все проблемы индивидуальны + зависти от скорости интернет соединения. Остальные пункты, например первоначальную сборку проекта в Android Studio, можно делать в фоне продолжая читать кодлаб. 
> - Возможно имеет смысл поменять 5 и 6 пункты местами чтобы не прыгать часто между IDE

**Comment by AppoNut** [comment]
1 - В самом начале 4го пункта дублируется "достаточно"
2 - Для iOS девелоперов может быть не очевидно как добавить эмульсине, чтобы запустить проект. Хотя бы текстом бы оставить подпись. Кнопок много, просто заблудиться
3 - Было бы неплохо добавить сюда же конфигурацию воркеров и студии

**Comment by Alex009** [comment]
добавить пояснение как проверить одинаковую ли JVM использует компилятор в студии и в xcode

можешь открыть activity monitor и посмотреть сколько там java процессов
если один то все гуд
если несколько - убей их и попробуй по новой скомпилить в xcode а потом в студии
если опять станет 2 - значит разные
смотри тогда в export - там JAVA_HOME какой

**Comment by Alex009** [comment]
> Отладка на андроиде не сразу заработала. Важный момент, который не отражен в самой кодлабе: если установлено несколько jdk, то Xcode будет запускать бил с рандомным. Поэтому важно оставить только jdk-11.
> Вся кодлаба заняла 1h 20m, из которых 20 минут было потрачено на определение причины запуска 4ых разных джава-тасков при нескольких попытках сблизить проект. Так бы за 60 минут управился, а время распределено примерно равномерно между пунктами (конкретно не считал)
> Отписал 3 момента в гитхабе и 4ым пунктом бы как раз историю про jdk и Xcode вставил бы.

**Comment by DevTchernov** [comment]
Ссылка с главной ведет просто на гитхаб компании, а надо наверное на этот репозиторий

**Comment by DevTchernov** [comment]
После установки JAVA_HOME в .zshenv не описано как проверить что все получилось, надо наверное из конца сразу сюда перенести

**Comment by DevTchernov** [comment]
На странице "запуск Андроид" могут быть не настроены симуляторы, вроде ничего сложного и студия сама предлагает, но хотя бы упомянуть нужно, а то складывается ощущение будто выбранный симулятор где-то в проекте запомнен и достаточно только "Run" нажать

**Comment by anton6tak** [comment]
- [ ]  Сделать сноску с пояснениями что Gradle Sync может пройти с ошибкой и тогда не будет конфигурации запуска андроида и задачи компиляции айоса + как с этим бороться
- [ ] Описать подробнее что нужно в .zshenv редактировать и как это можно делать (что не только nano можно использовать и пример контента в принципе показать) - "я обычно просто нахожу этот файл и открываю его через SublimeText и редактирую , тогда возник вопрос куда или где нужно вписать эту строку ?"
- [ ] Указать команду для самопроверки правильности настройки переменных окружения там же, где настраиваем переменную окружения "а именно на вот этом этапе “На Welcome экране выбираем Configure -> Default Project Structure. И в появившемся экране выбираем JDK Location из JAVA_HOME:” у меня нет такого , предлагает следущий AndroidStudio.app -> Contents -> jre -> jdk -> Contents"
- [ ] Описать как проверить какой JDK делает сборку Xcode
- [ ] Пояснить, что делать с SigningConfig "release" is missing required property "storePassword".
- [ ] В конце второго пункта, в "Проверка наличия всех необходимых переменных окружения" предлагаю добавить еще напоминалку "Открыть новую сессию терминала" т.к. в старой сессии новые переменные отображаться не будут.
- [ ] В пунктах 4 или 5 надо показать на скриншоте где именно находится вкладка с задачами Gradle
- [ ] В пункте 5 в главе "Компиляция MultiPlatformLibrary.framework" можно немного пояснить что такое компиляция kotlin модуля. Мол, эта задача запускает компилятор Kotlin Native, который компилирует common и ios код в нативную статическую библиотеку, которая упаковывается в статический фреймворк вместе с ресурсами модуля, который и подключается к проекту xcode.
- [ ] В пункте 6 про отладку на Android я бы первым абзацем просто написал, что для Android работа с дебаггером в общем коде ничем не отличается от привычного использования.
- [ ] В некоторых местах надо указывать, что это актуально только для macOS (переменные окружения под windows указываются иначе)
- [ ] Настройка окружения - CocoaPods - по офф доке не удалось установить, воспользовался brew: {{brew cleanup -d -v }} brew install cocoapods (Добавить, что можно установить и таким образом)
- [ ] Configure -> Default Project Structure - путь в переменной JAVA_HOME отличается от пути который выводится в терминале командой export после изменения ~/.zshenv. Проблему решил редактированием файла nano .bash_profile
- [ ] Возможно имеет смысл поменять 5 и 6 пункты местами чтобы не прыгать часто между IDE
- [ ] Добавить описание, как создавать симулятор
- [ ] Было бы неплохо добавить сюда же конфигурацию воркеров и студии 
- [ ] Добавить пояснение как проверить одинаковую ли JVM использует компилятор в  Android Studio и в Xcode (открыть Activity Monitor и посмотреть сколько там java процессов: если один то все гуд, если несколько - убить их и попробовать по новой скомпилить в xcode а потом в студии. Если опять станет 2 - значит разные. Тогда смотреть в export - там JAVA_HOME какой)
- [ ] Если установлено несколько jdk, то Xcode будет запускать билд с рандомным. Поэтому важно оставить только jdk-11.
- [ ] Ссылка с главной ведет просто на гитхаб компании, а надо наверное на этот репозиторий
- [ ] После установки JAVA_HOME в .zshenv не описано как проверить что все получилось
- [ ] ./gradlew syncMultiPlatformLibraryDebugFrameworkIosArm64 команда для не работает из за настроек zsh , необходимо зайти в файл .zshenv открыть редактором и раскомментировать в самом начале
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH <- раскомментировать это. Повторяем  ./gradlew syncMultiPlatformLibraryDebugFrameworkIosX64 должно работать , если нет то менять настройки iTerm в разделе defaults
- [ ] Если по какой-то причине поставилась не 11 jdk, то смотреть сюда https://java.tutorials24x7.com/blog/how-to-switch-java-version-on-mac. Описать ошибку и как решать 
- [ ] Ошибка после pod install: error: Signing for "ios-app" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'ios-app' from project 'ios-app')
"Есть скриншот если нужен вышлю"
идем в настройки проекта -> TARGET -> ios-app -> BundleIdentifier и меняем org.example.app на другой Пример "org.example.app.my"
- [ ] Исправить опечатки (В самом начале 4го пункта дублируется "достаточно")

**Comment by kramlex** [comment]
https://kmm.icerock.dev/docs/for-ios-devs/gradle новая ссылка на "Gradle для iOS"
